use_frameworks!

platform :ios, '11.0'

target 'ClosureReactor_Example' do
  pod 'ClosureReactor', :path => '../'

  target 'ClosureReactor_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
